-- phpMyAdmin SQL Dump
-- version 4.7.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: 09 Mei 2019 pada 07.25
-- Versi Server: 10.1.28-MariaDB
-- PHP Version: 7.1.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `tobat`
--

-- --------------------------------------------------------

--
-- Struktur dari tabel `obat`
--

CREATE TABLE `obat` (
  `id_obat` int(11) NOT NULL,
  `nama_obat` varchar(255) NOT NULL,
  `deskripsi_obat` varchar(535) NOT NULL,
  `foto_obat` varchar(255) NOT NULL DEFAULT 'default_obat.jpg',
  `kategori` varchar(255) NOT NULL,
  `komposisi` varchar(255) NOT NULL,
  `indikasi` varchar(255) NOT NULL,
  `dosis` varchar(255) NOT NULL,
  `penyajian` varchar(255) NOT NULL,
  `cara` varchar(255) NOT NULL,
  `perhatian` varchar(255) NOT NULL,
  `efek` varchar(255) NOT NULL,
  `kemasan` varchar(255) NOT NULL,
  `pabrik` varchar(255) NOT NULL,
  `keterangan` varchar(255) NOT NULL,
  `referensi` varchar(255) NOT NULL,
  `harga` mediumint(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `obat`
--

INSERT INTO `obat` (`id_obat`, `nama_obat`, `deskripsi_obat`, `foto_obat`, `kategori`, `komposisi`, `indikasi`, `dosis`, `penyajian`, `cara`, `perhatian`, `efek`, `kemasan`, `pabrik`, `keterangan`, `referensi`, `harga`) VALUES
(6, 'FITKOM ANGGUR BTL', 'Memenuhi kebutuhan vitamin dan mineral pada anak anak usia pertumbuhan dengan rasa anggur', '800.800_5ed03a3a9d954480b4a9d32b7b07c267.jpg', 'Vitamin dan Mineral', 'vitamin a 1000IU, vitamin b1 1.4mg, vitamin b2 1.6 mg, vitamin b6 2 mg, vitamin b12 3 mcg, vitamin c 60 mg,  vitamin d3 100IU, vitamin e 5 mg, nicotinamid 9 mg, ca pantotenate 5 mg', 'memenuhi kebutuhan vitamin dan mineral pada anak usia pertumbuhan, membantu memelihara kesehatan anak, membantu memulihkan kondisi tubuh sehabis sakit.', '3x sehari 1 tablet hisap', 'setelah makan', '-', '-', '-', '1', 'Soho', 'Terakhir diperbarui pada 26 April 2019', 'Referensi FITKOM ANGGUR BTL diambil dari berbagai macam sumber.', 16088),
(7, 'STERIMAR NASAL SPRAY 50ML', 'Sterimar Nasal Spray merupakan obat semprot hidung yang digunakan untuk melembabkan membran nasal (hidung) yang kering dan meradang karena pilek, alergi, kelembaban yang rendah, dan iritasi hidung yang lainnya pada anak-anak maupun dewasa.STERIMAR NASAL SPRAY 50ML; \r\nmengandung larutan Sea Water dan Purified Water yaitu larutan isotonis yang memiliki fungsi meringankan inflamasi membran hidung dengan mengencerkan lendir (ingus) supaya mudah keluar sekaligus melembabkan hidung yang kering.', '8421.jpg', 'Dekongestan Nasal dan Preparat Nasal Lain', 'sea water 31,82 ml; purified water qsp 100 ml', 'membantu membersihkan ingus pada hidung anak (mulai 3 tahun) dan dewasa, membantu menjaga kelembaban pada membran hidung, membantu menjaga kebersihan hidung', '2-6 kali semprotan per hari tiap lubang hidung (atau lebih jika diperlukan). Disarankan untuk penggunaan sebelum tidur atau membersihkan hidung sehari-hari.', 'secara perlahan-lahan masukkan ujung botol sterimar ke dalam lubang hidung, tekan botol perlahan-lahan, biarkan kelebihan cairan keluar dari hidung sebelum dibersihkan, ulangi lagi lalu bersihkan ujung botol dengan air sabun dan keringkan', 'simpan di tempat sejuk dan kering, terhindar dari paparan sinar matahari langsung', '-', '-', '1', 'SOFIBEL: Laboratoires Fumouze', 'Terakhir diperbarui pada 26 April 2019', 'Referensi STERIMAR NASAL SPRAY 50ML diambil dari berbagai macam sumber.', 146144),
(8, 'CHANNA CAP 30S', '-', 'apotek_online_k24klik_201903180215144677_channa.jpeg', 'Suplemen dan Terapi Penunjang', '-', '-', '-', '-', '-', '-', '-', '30', '-', 'Terakhir diperbarui pada 26 April 2019', 'Referensi CHANNA CAP 30S diambil dari berbagai macam sumber.', 259545),
(9, 'OB HERBAL JUNIOR', 'Merupakan obat herbal plus madu dan meniran yang dapat meredakan batuk dan menghangatkan tenggorokan yang disebabkan karena masuk angin.', '7540678_d65fa701-41b5-4994-bf97-72e9c85d57b3.jpg', 'Obat Batuk dan Pilek', 'Tiap 10 ml mengandung ekstrak : Zingiberis Rhizoma (2,2 g) Menthae Folia (2,173 g) Phyllanthi Herba (0,5 g) Kaempferiae Rhizoma (0,5 g) Citrus Aurantifolli Fructus (0,5 g) Thymi Herba (0,5 g) Myristicae Semen (0,25 g) Glycyrrhizae Radix (0,178 g) Madu (0,', 'Meredakan batuk yang disebabkan karena masuk angin. Menghangatkan dan melegakan tenggorokan', 'Anak umur 6-12 tahun : 3 kali sehari 2 sendok takar (10 ml)', 'Sesudah makan', 'Simpan di tempat yang kering dan terlindung dari sinar matahari langsung', '-', '-', '1', '-', 'Terakhir diperbarui pada 26 April 2019', 'Referensi OB HERBAL JUNIOR diambil dari berbagai macam sumber.', 13354),
(10, 'DEXANTA TAB 100S', 'Sirup obat maag yang dapat mengatasi tukak lambung, kembung, dispepsia, heartburn, dan hiperasiditas.\r\n\r\nBeli Dexanta Syr 100ML di TOBAT Online dan dapatkan manfaatnya.', 'dexanta.png', 'Antasid, Obat Antirefluks & Antiulserasi', 'Koloidal Al(OH)3 200mg, Mg(OH)2 200mg, simethicone 20mg', 'Hiperasiditas, tukak lambung, kembung, dispepsia dan heartburn', '1-2 tab 3 x/hari', 'Berikan di antara waktu makan dan sebelum tidur malam', 'Simpan di tempat yang kering dan terlindung dari cahaya', 'Diet rendah fosfat dan disfungsi ginjal', 'Konstipaso, Diare obstruksi intestinal (dosis tnggi)', '10', 'Dexa Medica', 'Terakhir diperbarui pada 26 April 2019', 'Referensi DEXANTA TAB 100S diambil dari berbagai macam sumber.', 2662),
(11, 'MATOVIT TAB 30&#39;S/STR', 'MATOVIT TAB 30&#39;S/STR merupakan suplemen untuk pemeliharaan kesehatan mata. Tersedia dalam bentuk tablet yang didistribusikan oleh Soho.', '_1_.jpg', 'Suplemen dan Terapi Penunjang', 'Per Matovit tablet : beta-carotene 5 mg, bilberry dry extract 80 mg, retinol 1600 iu, vit E 40 mg, Per 5 ml Matovit syrup : bilbery dry ectract 40 mg, retinol 800 iu, beta-carotene 2.5 mg, vit E 40 mg.', 'Terapi suportif untuk memelihara kesehatan mata', '2-3 x sehari 1 kaplet', 'saat/sesudah makanan', 'simpan di tempat sejuk dan kering, terhindar dari paparan sinar matahari langsung', '-', '-', '30', 'Soho', 'Terakhir diperbarui pada 26 April 2019', 'Referensi MATOVIT TAB 30&#39;S/STR diambil dari berbagai macam sumber.', 48004),
(12, 'ANADEX TAB 100S', 'Anadex diproduksi oleh PT. Interbat dan telah terdaftar pada BPOM. Pada setiap tablet Anadex mengandung 500mg paracetamol, 15mg dextromethorphan HBr, 1mg chlorpheniramine maleat, dan 15mg phenylpropanolamine HCl. Kombinasi yang terkandung dalam Anadex tablet dapat digunakan untuk membantu meringankan gejala flu seperti demam, batuk, nyeri, bersin-bersin, dan hidung tersumbat. Anadex tidak untuk diberikan pada penderita yang memiliki riwayat hipertiroid, hipertensi, penyakit jantung koroner, dan nefropati serta MAOI.', 'ANADEX-BOX-100-TABLET-1.jpg', 'Obat Batuk dan Pilek', '500mg paracetamol, 15mg dextromethorphan HBr, 1mg chlorpheniramine maleat, 15mg phenylpropanolamine HCl', 'flu, batuk, demam, nyeri dan selesma', 'dewasa: 3-4 kali sehari 1 tablet', 'diminum sebelum atau sesudah makan', 'simpan pada tempat sejuk dan kering, terhindar dari paparan sinar matahari langsung', 'penyakit jantung, diabetes mellitus, glaukoma, gangguan fungsi hati dan ginjal, ibu hamil dan anak', 'mengantuk, mulut kering, pusing, ruam kulit, serangan seperti epilepsi pada pemberian dosis tinggi.', '100', 'INTERBAT', 'Terakhir diperbarui pada 26 April 2019', 'Referensi ANADEX TAB 100S diambil dari berbagai macam sumber.', 11880),
(13, 'SANADRYL DMP SYR 60ML', 'Sanadryl DMP merupakan kombinasi dextromethorphan HBr, Difenhidramin HCl, Amonium klorida dan Natrium sitrat.', 'SANADRYL-DMP-SIRUP-60-ML-1.jpg', 'Obat Batuk dan Pilek', 'Tiap 5 ml mengandung : dextromethorphan HBr 10 mg, Difenhidramin HCl 12,5 mg, Amonium Klorida 100 mg dan Natrium Sitrat 50 mg, Mentol 1 mg.', 'Untuk meringankan gejala batuk tidak berdahak yang menimbulkan rasa sakit atau batuk karena alergi.', 'Anak-anak 6-12 tahun : 5 ml, 3-4 kali sehari. Dewasa : 10 ml, 3-4 kali sehari. Atau menurut petunjuk dokter.', 'Diberikan bersama dengan makanan', 'Simpan pada suhu kamar', 'Penyakit hati, Asma, Glaukoma, MAOI, Hamil, Anak, Mempengaruhi kemampuan mengemudi/menjalankan mesin.', 'Mengantuk, pusing, gangguan koordinasi, sekresi saluran pernapasan mengental, mulut kering; kejang epileptiform (dosis besar)', '1', 'Sanbe Farma', 'Terakhir diperbarui pada 26 April 2019', 'Referensi SANADRYL DMP SYR 60ML diambil dari berbagai macam sumber.', 15299),
(14, 'BETADINE GARGLE 100ML', 'obat kumur', '26132_product_1508906238.jpg', 'Preparat Mulut/Tenggorokan', 'povidon iodida 1%', 'obat kumur antiseptik untuk rongga mulut seperti gigi berlubang, gusi bengkak, sakit tenggorokan, sariawan, bau mulut dan nafas tak segar', '15 ml, 3-5 kali sehari', 'Tuang ke tutup botol (15ml), kumur 30-60 detik', '-', 'Hipersensitif terhadap iodium, penderita thyroid, hamil dan menyusui', 'iritasi jika absorbsi berlebihan bisa mengganggu sistemik', '1', '-', 'Terakhir diperbarui pada 26 April 2019', 'Referensi BETADINE GARGLE 100ML diambil dari berbagai macam sumber.', 16305),
(15, 'MICROPORE 1/2 PMTG', 'Micropore adalah plester kertas bebas latex dan hypoallergenic yang lembut bagi kulit namun tetap merekat baik dengan residu adhesive yang minimal saat dilepaskan. Micropore sangat cocok untuk aplikasi berulang pada kulit sensitif, fragile dan pasien lansia. Tersedia juga dalam kemasan dispenser untuk memudahkan penggunaan', 'apotek_online_k24klik_2017040711114713_1425-Nexcare-Micropore-paper-tape1-2-inch.png', 'Alat Kesehatan Medis', '-', '-', '-', '-', '-', '-', '-', '1', '-', 'Terakhir diperbarui pada 26 April 2019', 'Referensi MICROPORE 1/2 PMTG diambil dari berbagai macam sumber.', 18975),
(16, 'WELLNESS OMEGA 3 FISH OIL TAB 150S', 'Kadar kolesterol dan tekanan darah yang tinggi dapat memicu timbulnya penyakit degeneratif yang merupakan salah satu penyebab kematian terbesar. Untuk menghindari penyakit tersebut sebaiknya melakukan perubahan pola hidup menjadi lebih sehat dan ditunjang dengan konsumsi suplemen alami seperti Wellness Omega 3. Wellness Omega 3 diproduksi oleh PT Natural Nutrindo. Wellness Omega 3 mengandung Omega-3 CIS Formula alamiah yang terbukti sangat efektif dibandingkan dengan Omega-3 Trans Formula. ', 'wellness.png', 'Suplemen dan Terapi Penunjang', 'omega 3 1000 mg, EPA 180 mg, DHA 120 mg, vitamin E 5 IU', 'Membantu menurunkan kadar LDL, kolesterol, dan trigliserida', '1 kapsul per hari', 'sesudah makan', '-', 'Hindari penggunaan pada wanita hamil dan menyusui. Selama penggunaan konsultasikan dengan dokter secara berkala. Suplemen tidak dapat menggantikan nutrisi dari makanan', '-', '150', '-', 'Terakhir diperbarui pada 26 April 2019', 'Referensi WELLNESS OMEGA 3 FISH OIL TAB 150S diambil dari berbagai macam sumber.', 360030),
(17, 'VICKS VAPORUB 10G', 'obat gosok untuk melegakan hidung tersumbat akibat pilek', '31cSRZpOzzL.jpg', 'Obat Batuk dan Pilek', 'camphor 2630 mg, menthol 1410 mg, eucalyptus oil 665 mg', 'hidung tersumbat karena pilek', 'digunakan sesuai dengan kebutuhan', 'gosokkan pada bagian dada dan punggung', '-', '-', '-', '1', '-', 'Terakhir diperbarui pada 26 April 2019', 'Referensi VICKS VAPORUB 10G diambil dari berbagai macam sumber.', 8158),
(18, 'BALJITOT MINYAK GOSOK 50ML', 'Minyak gosok Baljitot diproduksi oleh PT Ultra Sakti dan terdapat juga balsem. Minyak gosok Baljitot diformulasikan khusus dengan ekstrak jahe merah dan memberikan rasa hangat lebih lama dan efek panas berganda dengan aroma relaksasi yang menenangkan. Minyak gosok Baljitot mengandung metil salisilat untuk mengatasi nyeri, menthol dan champora yang berfungsi sebagai anti iritan, serta ekstrak jahe merah. Minyak gosok Baljitot cocok untuk pijat dan kerik.', '886832_baljitot_minyak_gosok_50.jpg', 'Obat Kulit Lain', 'Methyl salicylate 28%, Eucalyptus Oil 2%, Citronella Oil 3%, Menthol 1,5%, Eugenol 0,5%, Ekstrak Jahe merah 0,1%, Based ad 100%', 'Mengatasi pegal linu, nyeri otot, nyeri sendi, sakit punggung, encok, keseleo, memar, dan memperlancar peredaran darah', 'Sesuai kebutuhan', 'cocok untuk pijat dan kerik', '-', 'Hipersensitif. Hanya untuk pemakaian luar. Jauhkan dari jangkauan anak-anak', 'Reaksi alergi', '1', 'PT Ultra Sakti', 'Terakhir diperbarui pada 26 April 2019', 'Referensi BALJITOT MINYAK GOSOK 50ML diambil dari berbagai macam sumber.', 14375),
(19, 'PANADOL ANAK CHEW TAB', 'Panadol Anak Chew Tab merupakan obat dalam bentuk tablet kunyah berfungsi dalam meredakan demam dan nyeri ada anak usia 2 hingga 12 tahun. Panadol mengandung zat aktif Paracetamol yang memiliki aktivitas sebagai penurun demam/antipiretik dan pereda nyeri/analgesik yang bisa diperoleh tanpa resep dokter.', '8889.jpg', 'Analgesik (Non Opiat) dan Antipiretik', 'Paracetamol.', 'Meredakan sakit kepala, sakit gigi, nyeri otot (mialgia), & demam yang menyertai flu & demam pasca vaksinasi.', 'Anak 6-12 tahun : 2-4 tab, Anak 2-5 tahun 1-2 tab. Diberikan 3-4 kali perhari dengan interval pemberian tiap 4 jam.', 'Dapat diberikan bersama atau tanpa makanan.', '-', 'Pasien dengan penyakit ginjal. Dpt meningkatkan risiko gangguan fungsi hati pada pasien yang mengonsumsi alkohol. Penggunaan bersama dengan obat lain yang mengandung parasetamol.', 'Kerusakan hati pada penggunaan jangka lama, dosis besar. Reaksi hipersensitivitas seperti kemerahan, gatal, pengelupasan kulit; gangguan pernapasan (krn aspirin & OAINS), pembengkakan bibir, lidah, tenggorokan, & wajah; sariawan, memar, perdarahan.', '10', 'Sterling', 'Terakhir diperbarui pada 26 April 2019', 'Referensi PANADOL ANAK CHEW TAB diambil dari berbagai macam sumber.', 13585),
(20, 'BETADINE SABUN CAIR 60ML', 'Betadine sabun cair antiseptik yang digunakan untuk mengatasi masalah pada kulit seperti jerawat, gatal-gatal dan untuk menjaga kesehatan kulit.', '00000697_BetadineSabunCair60ML-400x400.jpg', 'Antiseptik dan Desinfektan Kulit', 'Povidon iodine 7,5%', 'Untuk mandi, untuk mengobati jerawat dan gatal-gatal di kulit,Membersihkan kulit dan tangan sebelum melakukan operasi, membersihkan kulit yang akan di operasi', 'Sesuai kebutuhan', 'Gunakan Betadine sabun cair antiseptik seperti anda menggunakan sabun mandi biasa', '-', 'Hanya untuk pemakaian luar', 'Reaksi hipersensitif terhadap iodium', '1', 'Mahakam Beta Farma', 'Terakhir diperbarui pada 30 April 2019', 'Referensi BETADINE SABUN CAIR 60ML diambil dari berbagai macam sumber.', 26892),
(22, 'ALKOHOL 70% IKA 100ML', 'Cairan antiseptik', 'Alkohol-ika.png', 'Antiseptik dan Desinfektan Kulit', 'Larutan alkohol dengan kadar 70%', 'Antiseptik, sterilisasi alat medis', 'Dituang pada kassa steril atau kapas, lalu diusapkan pada luka atau alat medis', 'Dioleskan', '-', '-', '-', '1', '-', 'Terakhir diperbarui pada 02 Mei 2019', 'Referensi ALKOHOL 70% IKA 100ML diambil dari berbagai macam sumber.', 20909),
(23, 'PK SEINO 5G', 'PK SEINO 5G merupakan serbuk antiseptik untuk pembersih kulit yang terkena infeksi jamur, bakteri atau alergi. \r\nBeli PK SEINO 5G di TOBAT Online dan dapatkan manfaatnya.', 'Peka.png', 'Antiseptik dan Desinfektan Kulit', 'Permanganas kalicus', 'Untuk membersihkan borok/koreng, kompres pada eksema, infeksi  jamur atau kutu air.', 'Digunakan sesuai dengan kebutuhan', 'Larutan 1:1000 dalam air,untuk membersihkan koreng. Larutan 1:5000 dalam air, untuk kompres eksema. Larutan 1:100 dalam air, untuk infeksi jamur/kutu air', 'Simpan di tempat sejuk dan kering, terhindar dari paparan sinar matahari langsung', 'Hindari penutupan rapat pada penggunaannya', 'Iritasi lokal, pewarnaan pada kulit dan pakaian', '1', 'Seino', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi PK SEINO 5G diambil dari berbagai macam sumber. ', 4026),
(24, 'ICHTYOL SALEP NUFARINDO 15G', 'Ichtyol merupakan obat salep kulit yang dikenal dengan Salep Hitam dan digunakan untuk mengobati eksim, psoriasis, jerawat atau bisul. Ichtyol mengandung zat aktif Ichtammol yang berasal dari destilat minyak mentah di mana terdapat kandungan belerang di dalamnya. Ichtammol memiliki sifat anti bakteri, anti fungal, dan antiinflamasi.', 'Itchi.png', 'Antiseptik dan Desinfektan Kulit', 'Ichtammol', 'Eksim, psoriasis, jerawat, bisul.', '2-3 kali sehari', 'Dioleskan tipis-tipis pada area kulit yang sakit', 'Simpan di bawah suhu 30, terhindar dari sinar matahari langsung', 'Penggunaan pada ibu hamil sebaiknya dikonsultasikan kepada dokter', 'Penggunaan berlebihan: iritasi berat', '1', 'Nufarindo', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi ICHTYOL SALEP NUFARINDO 15G diambil dari nutriclub.co.id. ', 10980),
(25, 'DETTOL LIQ REG 250ML', 'Antiseptik cair', 'Dettol.png', 'Antiseptik dan Desinfektan Kulit', 'Chloroxylenol 4,8 %', 'Mempercepat penyembuhan luka, lecet, gigitan serangga, cuci tangan, desinfektan', '-', 'Dilarutkan dalam air', '-', '-', '-', '1', '-', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi DETTOL LIQ REG 250ML diambil dari berbagai macam sumber. ', 42556),
(26, 'LACTACYD BABY 60ML', 'Produk untuk membersihkan , merawat dan menjaga kulit bayi tetap bersih, segar dan lembut', 'lactacyd.png', 'Antiseptik dan Desinfektan Kulit', 'Aquademineralisata, ammonium triethanolamine sulfates, ethyleneglycol stearate, diethyleneglycol stearate, hydrogenated peanut oil, sodium hydroxide, lactoserum, ethylhydroxyethylcellulose, natural orange flavour, sodium methylhydroxybenzoate, lactic acid', 'Merawat kulit yang terkena ruam popok', 'Untuk memandikan bayi: encerkan 3-4 sendok penuh dalam wadah mandi.', 'Mandikan bayi seperti biasa, gosok dengan lembut. Bilas dengan seksama. Untuk membersihkan wajah dan perawatan kulit gunakan seperti memakai sabun cair, untuk merawat kulit kepala gunakan seperti memakai shampoo.', '-', '-', '-', '1', 'Pharma Health Care', 'Terakhir diperbarui pada 02 Mei 2019', 'Referensi LACTACYD BABY 60ML diambil dari berbagai macam sumber. ', 30360),
(27, 'BETADINE SOL 5ML', 'Betadine sol 5ml merupakan larutan untuk membersihkan dan mengobati luka, juga sebagai desinfektan pada luka terbuka.\r\n\r\nBeli Betadine Sol 5ml di TOBAT Online dan dapatkan manfaatnya', 'Betadine.png', 'Antiseptik dan Desinfektan Kulit', 'Povidon iodida 10%', 'Desinfektan sebelum atau sesudah operasi, mencegah dan pengobatan infeksi pada luka, irigasi dan kompres luka bernanah', 'Sesuai kebutuhan', 'Dioleskan, untuk irigasi (mencuci), untuk kompres', '-', 'Hipersensitif terhadap iodium', 'Iritasi', '1', '-', 'Terakhir diperbarui pada 02 Mei 2019', 'Referensi BETADINE SOL 5ML diambil dari berbagai macam sumber. ', 4671),
(28, 'OXOFERIN SOL 0,001% 30ML', 'OXOFERIN SOL 0,001% 30ML merupakan larutan yang dapat digunakan untuk luka terinfeksi, penyembuhan luka yang lambat sesudah traumatik atau sesudah operasi, ulkus dekubitus, ulkus kaki kronis pada insufisiensi vena, ulkus dan luka akibat aliran darah arteri, mikroangiopati akibat diabetes atau akibat kelainan, ulkus dibetik, ganggren serta luka bakar. \r\nBeli OXOFERIN SOL 0,001% 30ML di TOBAT Online dan dapatkan manfaatnya.', 'oxoferin.png', 'Antiseptik dan Desinfektan Kulit', 'Anion Tetra Klorodeka-oksigen kompleks / Tetra chlorodeca-oxygen anion complex', 'Luka terinfeksi, penyembuhan luka yang lambat sesudah traumatik atau sesudah operasi, ulkus dekubitus, ulkus kaki kronis pada insufisiensi vena, ulkus & luka akibat aliran darah arteri, mikroangiopati akibat diabetes atau akibat kelainan, ulkus dibetik, g', '2 kali sehari 5-10 mL.', '-', '-', '-', '-', '1', 'PHAROS', 'Terakhir diperbarui pada 02 Mei 2019', 'Referensi OXOFERIN SOL 0,001% 30ML diambil dari berbagai macam sumber. ', 99546),
(29, 'RIVANOL ONE MED 100ML', 'Rivanol merupakan cairan desinfektan yang digunakan untuk membersihkan luka.\r\nBeli Rivanol One Med 100ML di TOBAT Online dan dapatkan manfaatnya.', 'rivanol.png', 'Antiseptik dan Desinfektan Kulit', 'Etakridina laktat 0,1% dalam air.', 'Untuk membersihkan luka', 'Sesuai kebutuhan', 'Bubuhkan rivanol pada kapas, kemudian usapkan pada luka. bisa untuk membasuh luka', '-', '-', '-', '1', 'One med', 'Terakhir diperbarui pada 02 Mei 2019', 'Referensi RIVANOL ONE MED 100ML diambil dari berbagai macam sumber. ', 4092),
(30, 'BLACKMORES MULTIVITAMIN DAN MINERALS TAB 120S BTL', 'Blackmores Multivitamin dan Minerals tablet merupakan suplemen yang mengandung vitamin esensial dan berbagai mineral yang membantu memenuhi kebutuhan nutrisi setiap hari, bermanfaat memelihara kesehatan, dan mengandung vitamin B kompleks untuk menambah stamina. \r\nBeli Blackmores Multivitamin dan Minerals tab 120&#39;S di TOBAT Online dan dapatkan manfaatnya.', 'blackmores.png', 'Vitamin dan Mineral', 'Vitamin C (Ascorbic acid) 180 mg, Vitamin B3 (Nicotinamide) 60 mg, Vitamin B6 (Pyridoxine hydrochloride) 10 mg, Vitamin B2 (Riboflavin) 8.5 mg, Vitamin B1 (Thiamine hydrochloride) 7.5 mg, Calcium (from Calcium carbonate) 40 mg, Vitamin B5 (Pantothenic aci', 'Membantu memelihara kesehatan, mencukupi kebutuhan vitamin dan mineral yang tidak diperoleh dari makanan, dan menambah stamina tubuh.', '1 kali sehari', 'Berikan setelah makan', 'Simpan di tempat sejuk dan kering, serta terhindar dari sinar matahari langsung', '-', '-', '120', 'Kalbe Farma', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi BLACKMORES MULTIVITAMIN DAN MINERALS TAB 120S BTL diambil dari berbagai macam sumber. ', 445000),
(31, 'ASEPSO FRESH SOAP 85G', 'Asepso merupakan sabun antiseptik dengan active deodoriseryang digunakan untuk mengurangi biang keringat dan membersihkan kulit dari kuman penyebab penyakit kulit. \r\nBeli Asepso Fresh SOAP 85G di TOBAT Online dan dapatkan manfaatnya', 'asepso.png', 'Antiseptik dan Desinfektan Kulit', '-', 'Mengurangi biang keringat, infeksi kulit, maupun penyebaran kuman-kuman berbahaya ', 'Sesuai kebutuhan', 'Gunakan seperti pada pemakaian sabun mandi biasa', '-', '-', '-', '1', 'Triple Acne Corporation', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi ASEPSO FRESH SOAP 85G diambil dari berbagai macam sumber. ', 7854),
(32, 'SANGOBION CAP 10&#39;S', 'SANGOBION CAP 10&#39;S adalah vitamin & zat besi penambah darah untuk mengatasi anemia (kurang darah) karena kekurangan zat besi dan mineral. Produk ini mengandung zat besi, vitamin dan mineral yang penting dalam pembentukan sel darah merah, terutama Hemoglobin (Hb) yang berperan mengangkut oksigen ke seluruh tubuh sehingga dapat membantu pembentukan sel darah merah untuk mengatasi anemia (kurang darah). Sangobion juga mengandung Vit.C yang dapat membantu meningkatkan penyerapan zat besi dan merupakan suplemen zat besi pertama ya', 'sangobion.png', 'Vitamin dan Mineral', '1 kapsul mengandung Ferrous Gluconate 250 mg Manganese Sulfate 0, 2 mg Copper Sulfate 0, 2 mg Vitamin C 50, 0 mg Asam Folat / Folic Acid 1,0 mg Vitamin B 12 7, 5 mcg ', 'Anemia karena kekurangan zat besi dan mineral lain yang membantu pembentukan darah', '1 kapsul sehari pada waktu atau sesudah makan. Dapat dikonsumsi mulai dari 3 hari sebelum dan selama periode menstruasi', 'Dapat dikonsumsi mulai dari 3 hari sebelum dan selama periode menstruasi', 'Simpan di tempat sejuk dan kering, terhindar dari paparan sinar matahari langsung', 'Akumulasi zat besi, gangguan penggunaan zat besi', 'Nyeri lambung, muntah, konstipasi, diare, kolik', '10', 'Merck', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi SANGOBION CAP 10&#39;S diambil dari berbagai macam sumber. ', 14597),
(33, 'ZAMEL SYR', 'Vitamin dan mineral pada anak', 'zamel.png', 'Vitamin dan Mineral', 'Vit A 2000 IU, tiamine 5 mg, riboflavin 2 mg, pyridoxine 5 mg, cyanocobalamin 2 mcg, nicotinamide 10 mg, folic acid 15 mcg,choline 5 mg, inositol 12 mg,biotin 100 mcg, vitamin E 5 IU,Fe 5 mg,Zn 2,5 mg, Mg 35 mg, copper 300 mcg, selenium 20 mcg, chromium 1', 'Pencegahan dan pengobatan defisiensi vitamin atau mineral pada anak dalam masa pertumbuhan', '1-3 th : 1 x sehari 2,5 ml, 4-6 th:1 x sehari 5 ml, > 6 th: 1 x sehari 7,5 ml', 'Sesudah makan', '-', '-', '-', '1', '-', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi ZAMEL SYR diambil dari berbagai macam sumber. ', 50325),
(34, 'FOLAMIL TAB', 'Suplemen yang mengandung multivitamin dan mineral yang dibutuhkan oleh wanita hamil dan menyusui', 'folamil.png', 'Vitamin dan Mineral', 'Beta caroten 10.000iu, vitamin b1 mononitrat 10 mg, vitamin b2 2.5 mg, nicotinamid 20 mg, vitamin b6 15 mg, calcium pantotenate 7.5 mg, vitamin b12 4 mcg, vitamin c 100 mg, vitamin d 400 IU, folic acid 1 mg, potasium iodide 100 mcg, ferrous fumarate 90 mg', 'Nutrisi tambahan selama masa kehamilan dan setelah melahirkan', '1 x sehari 1 kaplet', 'Sesudah makan', '-', 'Pada penderita yang hipersensitif terhadap komponen-komponen obat, dan kandungan fluor dalah air minum/makanan > 0.7 ppm', '-', '8', 'Dexa Medica', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi FOLAMIL TAB diambil dari berbagai macam sumber. ', 7920),
(35, 'FOLDA TAB 30S', 'Kombinasi multivitamin dan mineral untuk wanita hamil dan nifas, untuk mendukung kesehatan pada ibu dan bayi.\r\nBeli Folda Tab 30S di TOBAT Online dan dapatkan manfaatnya.', 'folda.png', 'Vitamin dan Mineral', 'Asam folat 800mcg, DHA 30mg, Vitamin B12 12mcg', 'Memelihara kesehatan pada wanita hamil', '1 x sehari 1 tablet', 'Berikan setelah makan', 'Simpan di tempat yang sejuk dan kering, serta terlindung dari panas dan sinar matahari langsung', '-', '-', '30', 'Simex', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi FOLDA TAB 30S diambil dari berbagai macam sumber. ', 32340),
(36, 'FITKOM GUMMY VITAMIN C DAN ZINK 24G', 'Fitkom gummy vitamin C dan zinc merupakan suplemen untuk memenuhi kebutuhan vitamin dan mineral, pada anak-anak diusia pertumbuhan, membantu memelihara kesehatan anak-anak dan membantu memulihkan kondisi tubuh anak-anak sehabis sakit. Berbentuk tablet kunyah seperti jelly, dengan rasa manis yang disukai anak-anak', 'fitkom.png', 'Vitamin dan Mineral', 'Multivitamin, vitamin C, dan Zinc', 'Memenuhi kebutuhan vitamin dan mineral pada anak usia pertumbuhan, memelihara kesehatan anak, membantu memulihkan kondisi tubuh setelah sakit', '1-3 x sehari', 'Berikan setelah makan', '-', '-', '-', '10', '-', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi FITKOM GUMMY VITAMIN C DAN ZINK 24G diambil dari berbagai macam sumber. ', 8465),
(37, 'PROMAVIT TAB', 'Suplemen multivitamin dan mineral untuk ibu hamil.\r\nBeli Promavit Tablet di TOBAT Online dan dapatkan manfaatnya.', 'promavit.png', 'Vitamin dan Mineral', 'Tuna oil 179 mg, omega-3 fatty acids 64.5 mg, DHA 48.5 mg, EPA 12.5 mg, folic acid 400 mcg, vitamin A 345 IU, vitamin D3 34.5 IU, vitamin B12 0.5 mcg, vitamin B6 150 mcg, Ca carbonate 100 mg, Mg oxide 62.5 mg, Fe fumarate 23.5 mg', 'Suplemen multivitamin dan mineral untuk ibu hamil dan menyusui', '2 kapsul lunak per hari', 'Berikan pada saat makan', 'Simpan di tempat yang kering dan terlindung dari cahaya', '-', '-', '10', 'Lapi', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi PROMAVIT TAB diambil dari berbagai macam sumber. ', 43560),
(38, 'PROHELIC', 'Suplementasi vitamin dan mineral dengan asam lemak yang dibutuhkan ibu hamil dan ibu menyusui sebagai nutrisi. Beli PROHELIC di  TOBAT Online dan dapatkan manfaatnya  ', 'prohelic.png', 'Vitamin dan Mineral', 'Fe fumarate 90 mg, folic acid 0.8 mg, niacinamide 30 mg, vit B1 6 mg, vit B6 5 mg, vit B12 0.025 mg, fish oil 10% EPA & 50% DHA 200 mg.', 'Suplementasi vit & mineral dg asam lemak esensial yg dibutuhkan oleh ibu hamil & ibu menyusui. Sebagai nutrisi.', '1 Kapsul/hari', 'Dapat diberikan bersamaan dengan makanan agar diabsorpsi lebih baik atau jika timbul rasa tidak nyaman pada GI', 'Simpan di tempat yang sejuk, kering, dan terlindung dari cahaya', 'Hipersensitivitas terhadap salah satu komponen obat ini', 'Feses berwarna hitam. Jangan diberikan pada pasien yang mendapat transfusi darah berulang atau pasien dengan anemia yang tidak disebabkan karena defisiensi zat besi', '10', 'Promed', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi PROHELIC diambil dari berbagai macam sumber. ', 71467),
(39, 'DUROL TONIC 225ML', 'Suplemen untuk memenuhi kebutuhan akan vitamin dan mineral, serta zat besi.\r\nBeli Durol Tonic 225ML di TOBAT Online dan dapatkan manfaatnya.', 'durol.png', 'Vitamin dan Mineral', 'Per 15 mL Vit B1 2.5 mg, vit B2 1.5 mg, vit B6 1 mg, vit B12 10 mcg, vit B3 12.5 mcg, Na glycerophosphate 150 mg, K glycerophosphate 5 mg, manganese sulphate 2 mg, Ferrazone 76.92 mg, ethanol 0.735 mL.', 'Membantu memenuhi kebutuhan vitamin B kompleks, mineral, dan zat besi.', 'Dewasa : 1 x sehari 15 mL, Anak : 1 x sehari 5 ml', 'Dapat diberikan bersama atau setelah makan', 'Simpan di tempat yang sejuk dan kering serta terhindar dari panas dan sinar matahari langsung', '-', '-', '1', 'Actavis', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi DUROL TONIC 225ML diambil dari berbagai macam sumber. ', 26144),
(40, 'STERIMAR BABY NASAL SPRAY 50ML', 'Sterimar Baby Nasal Spray merupakan obat semprot hidung yang digunakan untuk melembabkan membran nasal (hidung) yang kering dan meradang karena pilek, alergi, kelembaban yang rendah, dan iritasi hidung yang lainnya pada bayi.Sterimar Baby Nasal Spray Mengandung larutan Sea Water dan Purified Water yaitu larutan isotonis yang memiliki fungsi meringankan inflamasi membran hidung dengan mengencerkan lendir (ingus) supaya mudah keluar sekaligus melembabkan hidung yang kering.', 'sterimar.png', 'Dekongestan Nasal dan Preparat Nasal Lain', 'Sea water 31,82 ml; purified water qsp 100 ml', 'Membantu membersihkan ingus pada hidung anak, membantu menjaga kelembaban pada membran hidung, membantu menjaga kebersihan hidung', '2-6 kali sehari', 'Baringkan bayi, secara perlahan-lahan masukkan ujung botol sterimar ke dalam lubang hidung, tekan botol perlahan-lahan, biarkan kelebihan cairan keluar dari hidung sebelum dibersihkan, ulangi lagi lalu bersihkan ujung botol dengan air sabun dan keringkan', 'Simpan di tempat sejuk dan kering, terhindar dari paparan sinar matahari langsung', '-', '-', '1', 'Laboratories Fumoze', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi STERIMAR BABY NASAL SPRAY 50ML diambil dari berbagai macam sumber. ', 158356),
(41, 'AFRIN NASAL SPRAY 15 ML', 'Afrin Nasal Spray merupakan obat semprot hidung yang digunakan untuk melembabkan membran nasal (hidung) yang kering dan meradang karena pilek dan melegakan hidung tersumbat. Afrin Nasal Spray mengandung larutan Oxy Metazoline Hidroklorida yaitu larutan isotonis yang memiliki fungsi meringankan inflamasi membran hidung dengan mengencerkan lendir (ingus) supaya mudah keluar sekaligus melembabkan hidung yang kering.', 'afrin.png', 'Dekongestan Nasal dan Preparat Nasal Lain', 'Oxy metazoline hydrochloride 0.5 mg', 'Kongesti (kesembaban) hidung dan nasofaring karena salesma (flu), sinusitis, hay fever atau alergi saluran napas bagian atas lainnya. Pengobatan tambahan pada infeksi telinga bangian tengah', '> 6 tahun: 2-3 semprot ke dalam tiap lubang hidung 2x/hr (pagi dan sore)', 'Posisi kepala tegak lurus, letakkan ujung lubang semprotan dalam lubang hidung tanpa menyumbat lubang hidung seluruhnya. Selama setiap pemberian pasien harus menekuk kepalanya sedikit kedepan dan hirup dengan cepat sambil memnecet botol', 'Simpan ditempat sejuk dan kering, terlindung dari cahaya matahari', 'Hipersensitifitas', 'Umumnya dapat ditolerir dengan baik. Efek samping biasanya ringan dan sementara dan berupa rasa terbakar, tersengat, bersin atau bertambahnya ingus', '1', 'Schering-Plough', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi AFRIN NASAL SPRAY 15 ML diambil dari berbagai macam sumber. ', 64299),
(42, 'AQUA MARIS BABY NASAL DROP 15ML', 'Dekongestan hidung pada bayi.', 'Aqua.png', 'Dekongestan Nasal dan Preparat Nasal Lain', 'Per mL : Air laut Adriatik (Adriatic sea water).', 'Dekongestan & pembersih hidung harian untuk mengatasi kekeringan pada hidung.', 'Bayi ', '-', '-', '-', '-', '1', 'Soho Industri Pharmasi', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi AQUA MARIS BABY NASAL DROP 15ML diambil dari berbagai macam sumber. ', 113135),
(43, 'NASONEX 140DOSIS NASAL SPRAY 50MCG/DOSIS', 'Nasonex Nasal Spray diproduksi oleh PT Merck Sharp & Dohme Pharma dan telah terdaftar di BPOM. Nasonex nasal spray mengandung Mometasone furoate. Mometasone Furoate mengobati dan mencegah gejala alergi pada hidung termasuk mampet, bersin, gatal, dan hidung meler. Nasonex juga dapat digunakan untuk pengobatan polip di hidung. Mometasone termasuk dalam golongan kortikosteroid yang bekerja dengan mengurangi reaksi peradangan di hidung akibat alergen atau iritasi. Jika gejalamu tidak berkurang setelah mengkonsumsi obat ini segerelah ', 'nasonex.png', 'Dekongestan Nasal dan Preparat Nasal Lain', 'Mometasone furoate', 'Rinitis alergi musiman atau tahunan sedang s/d berat pada dewasa remaja & anak 2-11 tahun', 'Dewasa dan anak > 12 tahun 2 semprot 1 x sehari pada tiap lubang hidung (dosis total 200 mcg). Anak 2-11 tahun 1 semprot pada tiap lubang hidung 1 x sehari (dosis total 100 mcg)', 'Disemprotkan ke lubang hidung', 'Simpan ditempat sejuk dan kering, terlindung dari cahaya matahari', 'TBC aktif, infeksi jamur, bakteri & virus sistemik yang tidak diobati atau herpes simpleks okular. Pasien dengan sistem imun yang tertekan. Hamil, laktasi, atau wanita usia subur', 'Pendarahan atau bercak darah pada hidung, faringitis, hidung terasa terbakar atau iritasi', '1', '-', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi NASONEX 140DOSIS NASAL SPRAY 50MCG/DOSIS diambil dari berbagai macam sumber. ', 384262),
(44, 'AQUA MARIS NASAL SPRAY 30ML', 'Spray untuk dekongestan hidung.', 'Aquaadult.png', 'Dekongestan Nasal dan Preparat Nasal Lain', 'Per mL : Air laut Adriatik (Adriatic sea water).', 'Dekongestan & pembersih hidung harian untuk mengatasi kekeringan pada hidung.', '> 1 tahun : 3-4 kali per hari,', '-', '-', '-', '-', '1', 'Soho Industri Pharmasi', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi AQUA MARIS NASAL SPRAY 30ML diambil dari berbagai macam sumber. ', 120780),
(45, 'BNS BREATHY NASAL SPRAY 30ML', 'Breathy Nasal Spray diproduksi oleh PT. Novell Pharmaceutical Lab-Indonesia dan telah terdaftar pada BPOM. Breathy Nasal Spray merupakan obat semprot hidung yang mengandung natrium chloride 6,5mg pada setiap ml. Breathy Nasal Spray digunakan untuk melembabkan membran hidung yang kering dan teriritasi karena pilek, alergi, kelembaban yang rendah, pendarahan hidung serta iritasi hidung minor lainnya. ', 'bns.png', 'Dekongestan Nasal dan Preparat Nasal Lain', 'Setiap ml mengandung natrium klorida 6,5mg', 'Melembabkan membran hidung yang kering dan teriritasi karena pilek, alergi, kelembaban yang rendah, pendarahan hidung serta iritasi hidung minor lainnya. ', 'Dewasa : 2-6kali semprot sehari pada setiap lubang hidung. anak dan bayi >1bln : 1 kali semprot sehari pada setiap lubang hidung ', 'Semprotkan pada setiap lubang hidung', '-', 'Jangan digunakan pada orang lain untuk menghindari penularan infeksi', '-', '1', 'NOVELL', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi BNS BREATHY NASAL SPRAY 30ML diambil dari berbagai macam sumber. ', 107360),
(46, 'AVAMYS NASAL SPRAY 120ML', 'Avamys merupakan obat semprot hidung yang digunakan untuk melembabkan membran nasal (hidung) yang kering dan meradang karena pilek dan melegakan hidung tersumbat. Avamys mengandung Fluticasone furoate yang bekerja dengan cara menghambat sintesis mediator penyebab inflamasi (peradangan), kemerahan, dan gatal-gatal dengan menghasilkan suatu protein anti-inflamasi. ', 'avamys.png', 'Dekongestan Nasal dan Preparat Nasal Lain', 'fluticasone furoate 27,5 mcg', 'Rhinorrhea, hidung tersumbat/gatal, & alergi rinitis.', 'Dewasa dan remaja =12 tahun dosis awal 2 sprays sekali sehari. dosis pemeliharaan: 1 spray sekali sehari. anak 2-11 tahun 1 spray sekali sehari, dosis pemeliharaan: 1 spray sekali sehari.', 'Kocok dahulu obat, dengan penutup yang masih tertutup. penutup alat semprot harus dalam keadaan tertutup ketika sedang dikocok, Lepaskan penutup dengan perlahan sambil menekan tombol aktuator dengan ibu jari dan jari telunjuk anda lalu tarik penutup Jauh.', 'Simpan ditempat sejuk dan kering, terlindung dari cahaya matahari', '-', 'Luka pada hidung', '1', '-', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi AVAMYS NASAL SPRAY 120ML diambil dari berbagai macam sumber. ', 223978),
(47, 'RESPIMER BABY DECONGESTANT NASAL SPRAY 60ML', '-', 'respimer.png', 'Dekongestan Nasal dan Preparat Nasal Lain', 'Air laut setara dgn NaCl 22g/L', 'Dekongestan, mukolitik pada bayi diatas 1 bulan.', 'Rinitis semprotkan selama 2-3 detik 2-3x per hari.', '-', '-', '-', '-', '1', 'Interbat', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi RESPIMER BABY DECONGESTANT NASAL SPRAY 60ML diambil dari farmasi-id.com. ', 181170),
(48, 'BETADINE COLD DEFENCE KIDS NASAL SPRAY 20ML', '-', 'betadine-cold.png', 'Dekongestan Nasal dan Preparat Nasal Lain', 'Larutan Garam dengan 1.2mg / ml Carrageenan', '-', '-', '-', '-', '-', '-', '1', 'Mahakam Beta Farma', 'Terakhir diperbarui pada 2 Mei 2019', 'Referensi BETADINE COLD DEFENCE KIDS NASAL SPRAY 20ML diambil dari berbagai macam sumber. ', 165000),
(49, 'NUTRIVISION 30S', 'NUTRIVISION yang diproduksi oleh Kalbe Farma berfungsi sebagai antioksidan sekaligus suplemen untuk mata. NUTRIVISION baik dalam menangkal radikal bebas dari paparan sinar matahari, radiasi TV atau komputer, polusi udara, atau karena merokok. NUTRIVISION juga dapat digunakan untuk mengurangi gangguan yang mungkin timbul bagi penderita penyakit sistemik seperti diabetes, atau apada usia lanjut. ', 'nutrivision.png', 'Suplemen dan Terapi Penunjang', 'GliSODin (superoxide dismutase) 37.5 mg, beta-carotene 5,000 iu, vit C 187.5 mg, vit E 50 iu, vit B2 6.25 mg, selenium 17.5 mcg, Zn 3.75 mg, chromium 30 mcg, lutein 2.5 mg, rutin 12.5 mg, quercetin 12.5 mg, taurine 25 mg, carrot root 25 mg, citrus bioflav', 'Suplemen utk membantu menjaga kesehatan mata; antioksidan.', '1 kali sehari 1 kapsul', 'Sebaiknya diberikan bersama makanan', '-', 'Hipersensitivitas thd gandum/gluten. Hamil & laktasi', '-', '30', 'Kalbe Farma', 'Terakhir diperbarui pada 29 Oktober 2018', 'Referensi NUTRIVISION 30S diambil dari berbagai macam sumber. ', 303600),
(50, 'INSOBETIC CAP 60S', 'Insobetic yang diproduksi oleh Pharmacore merupakan suplemen dan terapi penunjang yang ditujukan untuk pasien diabetes supaya kebutuhan akan vitamin B12 dan asam folat selama konsumsi obat anti diabetes jangka panjang tetap terpenuhi, selain itu juga sebagai nutrisi yang tepat dalam membantu menjaga kadar gula darah tetap normal. Chromium picolenat yang terkandung di dalamnya dapat membantu meningkatkan penggunaan glukosa menjadi energi oleh tubuh, sedangkan vanadium sitrat dan zinc picolinate sama-sama memegang peranan penting t', 'insobetic.png', 'Suplemen dan Terapi Penunjang', 'Chromium picolenat, magnesium aspartat, vanadium sitrat, zinc picolinate, copper glukonat, vitamin B kompleks, asam folat, ', 'Memenuhi nutrisi esensial untuk membantu menjaga kadar gula darah normal agar tidak terjadi risiko komplikasi. Untuk memenuhi kebutuhan vitamin B12 dan asam folat yang menurun akibat konsumsi obat anti diabetes jangka panjang', '1 x sehari 1 kapsul', 'Sebaiknya berikan setelah makan', 'Simpan pada suhu ruangan', '-', '-', '60', 'Pharmacore', 'Terakhir diperbarui pada 11 Desember 2018', 'Referensi INSOBETIC CAP 60S diambil dari berbagai macam sumber. ', 23804),
(51, 'COLIDAN 100MG CAP 30S', 'Colidan 100 mg merupakan suplemen makanan yang mengandung fucoidan 100 mg. Fucoidan dapat membantu memelihara kesehatan lambung, yang terbuat dari bahan herbal dari ekstrak ganggang laut yang berasal dari perairan laut lepas Okinawa, Jepang. Fucoidan bekerja dengan cara membentuk selaput pada dinding lambung, sehingga dapat melindungi dari iritasi akibat enzim dan asam lambung, serta dapat terhindar dari infeksi bakteri. Colidan dapat digunakan untuk orang yang sudah mengalami gangguan lambung ataupun belum pernah. Colidan yang d', 'colidan.png', 'Suplemen dan Terapi Penunjang', 'Fucoidan 100mg', 'Memelihara kesehatan lambung', '1 kapsul sehari', 'Sebelum/sesudah makan', 'Simpan pada suhu ruang dan terhindar dari sinar matahari langsung', '-', '-', '20', 'Pharos', 'Terakhir diperbarui pada 3 Mei 2019', 'Referensi COLIDAN 100MG CAP 30S diambil dari berbagai macam sumber. ', 79200),
(52, 'IMUNPED SYR 60ML', 'Imunped Syrup diproduksi oleh Darya Varia dan sudah terdaftar pada BPOM. Imunped merupakan produk vitamin dan mineral yang digunakan sebagai suplemen makanan untuk mencegah dan mengobati defisiensi zinc dan vitamin C. Imunped syrup khusus diformulasikan untuk anak-anak dengan varian rasa apel manis yang membuat anak-anak suka. Imunped syrup digunakan bersamaan dengan larutan oralit/larutan garam ketika terkena demam dan diare. Kandungan zinc yang terkandung dalam Imunped syrup membantu mengurangi keparahan demam dan diare, serta ', 'imunped.png', 'Suplemen dan Terapi Penunjang', 'Per 5 ml mengandung Zinc 10 mg dan vitamin C 100 mg', 'Untuk pencegahan dan pengobatan defisiensi zinc dan vitamin C', 'Anak 9-13 tahun: 5-10 ml (1-2 sdt); 4-8 thn: 5 ml (1 sdt); 1-3 thn: 2,5 ml', 'Dapat diberikan bersama atau tanpa makanan', '-', '-', '-', '1', 'DARYA VARIA', 'Terakhir diperbarui pada 3 Mei 2019', 'Referensi IMUNPED SYR 60ML diambil dari berbagai macam sumber. ', 54351),
(53, 'NOURISH SKIN TAB 60S', 'Suplemen untuk kulit', 'nurisskin.png', 'Suplemen dan Terapi Penunjang', 'Lyophilized Marine Protein Complex dan Collagen, OPC, super antioksidan dari ekstrak biji anggur merah, antioksidan lain seperti betacarotene, Vitamin C, Vitamin E, Selenium', 'Menjaga dan memelihara kesehatan kulit', 'Dosis pemeliharaan 1 tablet perhari', 'Sesudah makan', '-', 'Hipersensitif', '-', '60', 'Nutrisains - Pharos Indonesia', 'Terakhir diperbarui pada 3 Mei 2019', 'Referensi NOURISH SKIN TAB 60S diambil dari berbagai macam sumber. ', 505560),
(54, 'VEGEBLEND 21 JR BTL 30&#39;S', 'Memenuhi kebutuhan sayur pada anak dan meningkatkan nafsu makan anak', 'vegeblend.png', 'Suplemen dan Terapi Penunjang', '275 mg Sari sayur alami :brokoli, wortel, tomat, bit, bayam, ketimun, kubis Brussel, kol hijau, seledri, kale, asparagus, kol kembang, lada, bawang merah, peterseli, gandum, alfalfa, barley hijau, kacang polong, lobak, lobak cina 40 mg Serat sayur alami :', 'Kekurangan nutrisi sayuran,berkurangnya nafsu makan, tenaga dan stamina pada anak', 'Anak umur 1-5 thÃ‚ : 1 kapsul 1 kali/hari, umur 5-12 thÃ‚ : 1-2 kapsul 1 kali/hari', 'Sesudah makan Jika anak sulit menelan kapsul, dibuka kapsulnya, lalu isinya dicampur pada makanan/minuman favorit anak, misal : susu, bubur, madu, ice cream', '-', '-', '-', '1', 'Nutrindo Jaya Abadi', 'Terakhir diperbarui pada 4 Mei 2019', 'Referensi VEGEBLEND 21 JR BTL 30&#39;S diambil dari berbagai macam sumber. ', 132858),
(55, 'VITABUMIN MADU ALBUMIN 130ML', 'VITABUMIN adalah Perpaduan Madu + Ekstrak Albumin Ikan Gabus, diperkaya Temulawak dan Pegagan. Manfaat Madu kaya akan vitamin A, D, K, E dan mineral, rasanya manis tanpa pemanis buatan, Protein albumin dari ekstrak ikan gabus diperlukan oleh tubuh untuk pembentukan dan perbaikan jaringan sel tubuh agar anak tumbuh maksimal. Temulawak efektif sebagai penambah nafsu makan dan peningkat daya tahan tubuh anak, Pegagan adalah herbal yang efektif melancarkan sirkulasi oksigen dan nutrisi ke sel otak untuk meningkatkan kecerdasan anak. ', 'vitabumin.png', 'Suplemen dan Terapi Penunjang', 'Perpaduan madu, protein albumin dari ekstrak ikan gabus, temulawak, dan juga pegagan. ', 'Sebagai suplemen/Vtamin untuk menjaga daya tahan tubuh ', 'Anak usia 1-3 tahun 2 sendok teh 2 kali sehari, usia 3-12 tahun 2 sendok makan 3 kali sehari ', 'Madu vitabumin bisa diminum langsung ataupun dicampur minuman seperti susu, jus, teh maupun lainnya yang disukai anak', 'Simpan di tempat kering dan sejuk, serta terhindar dari panas dan sinar matahari langsung ', '-', '-', '1', 'Aksamala', 'Terakhir diperbarui pada 4 Mei 2019', 'Referensi VITABUMIN MADU ALBUMIN 130ML diambil dari berbagai macam sumber. ', 79860),
(56, 'VECTRINE DRY SYRUP 60ML 175MG/5ML', 'Vectrin Dry Syrup merupakan obat batuk dan pilek yang berfungsi sebagai pengencer dahak pada penyakit saluran pernafasan akut dan kronik. Beli Vectrin Dry Syrup di apotek online k24klik.com dan dapatkan manfaatnya.   ', 'vectrine.png', 'Obat Batuk dan Pilek', 'Erdosteine', 'Mukolitik, pengencer dahak pada penyakit saluran nafas akut dan kronik. ', 'Sir Dws & anak > 30 kg 10 mL 2 x/hr, 20-30 kg 5 mL 3 x/hr, 15-19 kg 5 mL 2 x/hr. ', 'Suspensikan terlebih dahulu dengan menambahkan air hingga terbentuk suspensi 60 ml.', 'Simpan pada suhu dibawah 30 derajat Celcius. Lindungi dari paparan sinar matahari langsung', 'Wanita hamil dan menyusui.', 'Tidak terlihat efek samping pada gastrointestinal maupun sistemik. ', '1', 'Dexa Medica', 'Terakhir diperbarui pada 4 Mei 2019', 'Referensi VECTRINE DRY SYRUP 60ML 175MG/5ML diambil dari berbagai macam sumber. ', 56883),
(57, 'ERDOBAT 300MG TAB 20S', 'Erdobat meupakan obat yang dapat digunakan untuk mukolitik dan sebagai sekretolitik pada gangguan saluran nafas akut dan kronik. Beli Erdobat 300 mg tab di K24Klik dan dapatkan manfaatnya. Deskripsi ERDOBAT 300 MG TAB 20S diambil dari berbagai macam sumber. Segala bentuk perbedaan penulisan obat adalah diluar tanggung jawab K24klik.', 'erdobat.png', 'Obat Batuk dan Pilek', 'Erdosteine', 'Mukolitik, sebagai sekretolitik pada gangguan saluran nafas akut dan kronik', '1 Tablet 2-3 kali/hari', 'Dapat diberikan bersamaan makanan untuk mengurangi rasa tidak nyaman pada gastrointestinal', '-', 'Pada gangguan hati yang ringan, dosis yang diberikan tidak boleh lebih dari 300 mg/hari. hamil. laktasi', 'Mual,muntah, nyeri perut, gangguan pengecapan, sakit kepala, terasa dingin, sesak nafas, kulit gatal, kemerahan', '20', 'Interbat', 'Terakhir diperbarui pada 4 Mei 2019', 'Referensi ERDOBAT 300MG TAB 20S diambil dari berbagai macam sumber. ', 8819),
(58, 'CITOCETIN SYR 60ML', 'Obat batuk dan pilek anak', 'citocetin.png', 'Obat Batuk dan Pilek', 'Acetaminophen 120mg, Guaiafenesin 25mg, Phenylpropanolamine HCl 3,5mg, Chlorpheniramine Maleate 0,5mg', 'Untuk meringankan gejala flu seperti demam, sakit kepala, hidung tersumbat dan bersin-bersin yang disertai batuk', 'Bayi usia dibawah 1 tahun 3 x sehari Â½ sendok takar (2,5 ml), Anak usia 1 â€“ 6 tahun 3 x sehari 1 sendok takar (5 ml), Anak usia 6 â€“ 12 tahun; 3 x sehari 2 sendok takar (10 ml), Dewasa 3 x sehari 4 sendok takar (20 ml)', 'Sesudah makan', '-', 'Hati-hati pada penderita dengan gangguan fungsi hati dan ginjal, glaukoma, hipertrofi prostat, hipertiroid dan retensi urin. Tidak dianjurkan penggunaan pada wanita hamil dan menyusui, kecuali atas petunjuk dokter. Selama minum obat ini tidak boleh mengen', 'Mengantuk, gangguan pencernaan, gangguan psikomotor, takikardi, aritmia, mulut kering, palpitasi, retensi urin. Penggunaan dosis besar dan jangka panjang menyebabkan kerusakan hati. ', '1', 'CIUBROS FARMA', 'Terakhir diperbarui pada 4 Mei 2019', 'Referensi CITOCETIN SYR 60ML diambil dari berbagai macam sumber. ', 7260),
(59, 'PROCOLD FLU DAN BATUK TAB 6S', 'Membantu meringankan gejala flu seperti demam, bersin-bersin, hidung tersumbat, sakit kepala, dan batuk tidak berdahak. \r\n\r\n\r\nBeli Procold Flu Dan Batuk Tab 6S di TOBAT Online dan dapatkan manfaatnya.', 'procold.png', 'Obat Batuk dan Pilek', 'Paracetamol 500mg, dextromethorphan HBr 10mg, Pseudoefedrin HCl 30mg', 'Membantu meringankan gejala flu seperti demam, bersin-bersin, hidung tersumbat, sakit kepala, dan batuk tidak berdahak.', 'Dewasa dan anak >12 tahun : 3 x sehari 1 tablet, anak 6-12 tahun : 3 x sehari 1/2 tablet', 'Berikan setelah makan', 'Simpan di tempat yang sejuk dan kering, serta terlindung dari panas dan sinar matahari langsung', 'Tidak dianjurkan untuk anak-anak, wanita hamil dan menyusui, penderita hipertensi, penderita DM dan kardiovaskular, tidak boleh melebihi dosis yang dianjurkan', 'Dapat menyebabkan kantuk', '6', 'Kalbe Farma', 'Terakhir diperbarui pada 4 Mei 2019', 'Referensi PROCOLD FLU DAN BATUK TAB 6S diambil dari berbagai macam sumber. ', 3562),
(60, 'SILADEX BATUK PILEK 30ML', 'Siladex Batuk Pilek merupakan obat yang digunakan untuk mengatasi batuk yang disertai dahak dan meringankan pilek.\r\n', 'siladex.png', 'Obat Batuk dan Pilek', 'Tiap ml sirop: dextromethorphan HBr 7,5 mg, doksilamina suksinat 2 mg, pseudoefedarina-HCI 15 mg ', 'Batuk berdahak disertai pilek', '> 10 th : 3 x 5 ml ; 5-10 th : 3 x 2,5 ml', '-', 'Simpan di tempat sejuk dan kering, terhindar dari paparan sinar matahari langsung', 'Galukoma, penyakit jantung, tau hati asma, DM, hamil, mengganggu kemampuan mengemudi atau mengoperasikan mesin ', 'Gangguan GI, mengantuk, pusing, penglihatan kabur, mulut kering, dada terasa sesak, tinitus, sakit kepala, serangan spt epilepsi ', '1', 'KONIMEX', 'Terakhir diperbarui pada 4 Mei 2019', 'Referensi SILADEX BATUK PILEK 30ML diambil dari berbagai macam sumber. ', 7828),
(61, 'DEXANTA SYR 100ML', 'Dexanta Syrup diproduksi oleh PT. Dexa Medica dan telah terdaftar pada BPOM. Pada setiap 5ml Dexanta Syrup mengandung 200mg koloidal aluminium hidroksida, 200mg magnesium hidroksida dan 20mg simethicone. Dexanta Syrup merupakan obat antasida yang dapat digunakan untuk meredakan hiperasiditas (produksi asam hidroklorat dan dan cairan lain seperti pepsin yang berlebih pada lambung), tukak lambung, kembung, dispepsia (nyeri perut atau dada akibat adanya gas atau rasa terbakar) dan heartburn.', 'dexantasirop.png', 'Antasid, Obat Antirefluks & Antiulserasi', 'Per 5 ml suspensi mengandung koloidal aluminium hidroksida 200mg, magnesium hidroksida 200mg, simethicone 20mg', 'Hiperasiditas, tukak lambung, kembung, dispepsia, heartburn', '3-4 kali sehari 1-2 sendok takar (5ml)', 'Diminum diantara waktu makan dan sebelum tidur malam', '-', 'Diet rendah fosfat, disfungsi ginjal', 'Konstipasi, diare, obstruksi intestinal (pada dosis besar)', '1', '-', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi DEXANTA SYR 100ML diambil dari berbagai macam sumber. ', 20040),
(62, 'GASTRIDIN TAB', 'GASTRIDIN TAB mengandung zat aktif Ranitidin. Produk ini dapat digunakan untuk tukak lambung dan duodenum. serta Sindroma Zollinger-Ellison. Tersedia dalam bentuk tablet yang didistribusikan oleh Interbat. \r\nBeli GASTRIDIN TAB di TOBAT Online dan dapatkan manfaatnya.', 'gastridin.png', 'Antasid, Obat Antirefluks & Antiulserasi', 'Ranitidine HCl.', 'Tukak lambung & duodenum. Sindroma Zollinger-Ellison.', 'Dewasa : Tukak lambung/duodenum : 150 mg 2 x/hari selama 4 minggu atau 5-6 minggu bila perlu. Sindroma Zollinger-Ellison : Awal 150 mg 3 x/hari. Ditingkatkan 600-900 mg/hari.', 'Diberikan bersama atau tanpa makanan.', 'Simpan di tempat yang sejuk dan kering serta terhindar dari sinar matahari langsung.', 'Gangguan GI, ginjal, hamil, laktasi.', 'Sakit kepala, pusing. Gangguan GI, ruam kulit.', '10', 'Interbat', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi GASTRIDIN TAB diambil dari berbagai macam sumber. ', 7405);
INSERT INTO `obat` (`id_obat`, `nama_obat`, `deskripsi_obat`, `foto_obat`, `kategori`, `komposisi`, `indikasi`, `dosis`, `penyajian`, `cara`, `perhatian`, `efek`, `kemasan`, `pabrik`, `keterangan`, `referensi`, `harga`) VALUES
(63, 'PROGASTRIC TAB 200S', 'Tablet Progastric diproduksi oleh Combiphar dan sudah terdaftar di BPOM.Tiap Tablet Progastric mengandung Al(OH)3, Mg(OH)2, Mg trisilicate, dan simethicone. Alumunium hidroksida merupakan senyawa anorganik yang termasuk golongan antasida, begitupun dengan magnesium hidroksida. Mg(OH)2 adalah antasida yang bekerja dengan menetralkan asam lambung, sehingga mengurangi efek destruktif asam lambung. Efek ini diperpanjang oleh antasida kerja lambat Al(OH)3. Disamping itu, efek katartik Mg (OH)2 dan efek konstipasi Al(OH)3 dapat saling ', 'prograstric.png', 'Antasid, Obat Antirefluks & Antiulserasi', 'Koloid kering Al(OH)3 250 mg, Mg(OH)2 120 mg, Mg trisilicate 120 mg, simethicone 40 mg.', 'Gangguan lambung. Mual yang berhubungan dengan hiperasiditas. Tukak lambung dan tukak usus 12 jari', '1-2 tablet 3 x sehari & 1-2 tablet sebelum tidur', 'Berikan saat makan & sebelum tidur malam', 'Simpan pada tempat kering dengan suhu kamar, jauhkan dari paparan sinar matahari langsung', 'Gangguan ginjal. Penggunaan jangka panjang > 2 minggu tidak dianjurkan. Anak', 'Konstipasi, diare, mual, muntah', '10', 'COMBIPHAR', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi PROGASTRIC TAB 200S diambil dari berbagai macam sumber. ', 4158),
(64, 'FARMACROL F SYR 100ML', 'Farmacrol Forte merupakan obat yang digunakan untuk terapi dyspepsia (maag) dengan kombinasi antara antasida dengan metilpolisiloksan. Antasida yang mengandung magnesium (Mg trisilikat) dan aluminium (Al(OH)) yang relatif tidak larut dalam air dapat bekerja lama bila berada dalam lambung sehingga mampu menetralkan asam lambung dan menginaktifkan pepsin yang menginduksi nyeri ulu hati akibat iritasi oleh asam. Metilpolisiloksan aktif ditambahkan pada antasida untuk meringankan kembung atau sebagai antibuih. ', 'farmacrol.png', 'Antasid, Obat Antirefluks & Antiulserasi', 'Metilpolisiloksan aktif 125 mg, magnesium hidroksida 100 mg, aluminium hidroksida setara dengan aluminium oksida 200 mg', 'Mengurangi gejala-gejala yang berhubungan dengan kelebihan asam lambung, gastritis, tukak usus dua belas jari, dengan gejala-gejala seperti mual, nyeri lambung, nyeri ulu hati, kembung dan perasaan penuh pada lambung', 'Dewasa 1 sendok teh, 3-4 kali sehari, anak-anak 1/2 sendok teh 3-4 kali sehari', '1 jam sebelum makan dan sebelum tidur', 'Simpan di tempat sejuk dan kering, terhindar dari sinar matahari langsung', 'Jangan di berikan pada penderita gangguan fungsi ginjal yang berat, karena dapat menimbulkan hipermagnesia (kadar magnesium dalam darah meningkat)', 'Sembelit, diare, mual, muntah', '1', '-', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi FARMACROL F SYR 100ML diambil dari berbagai macam sumber. ', 52338),
(65, 'MUCOSTA 100MG TAB', 'Mucosta merupakan obat yang digunakan untuk mengobati tukak dan peradangan pada mukosa lambung (gastristis) akibat produksi asam lambung yang berlebihan. Mucosta mengandung zat aktif Rebamipide yaitu asam amino turunan kuinolon yang bekerja dengan meningkatkan sistem pertahanan dan perlindungan mukosa dengan mengaktifkan gen yang mengkode siklooksigenase-2 sehingga memberika efek sitoprotektif terhadap mukosa lambung. Rebamipide juga dapat meningkatkan jumlah lendir lambung dan merangsang aliran darah pada mukosa supaya membantu ', 'mucosta.png', 'Antasid, Obat Antirefluks & Antiulserasi', 'Rebamipide', 'Terapi kombinasi dengan penghambat pompa proton, antikolinergik atau antagonis H2 untuk tukak lambung', '3 x sehari 1 tablet', 'Sebelum/sesudah makan', 'Simpan di tempat sejuk dan kering, terhindar dari sinar matahari langsung', 'Hipersensitif', 'Konstipasi, mual muntah, pendarahan, rasa terbakar', '10', '-', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi MUCOSTA 100MG TAB diambil dari berbagai macam sumber. ', 6496),
(66, 'MYLANTA LIQ 150ML', 'Mylanta Liquid merupakan obat yang digunakan untuk mengatasi penyakit-penyakit yang disebabkan oleh kelebihan produksi asam lambung, seperti sakit maag dan tukak lambung. Setiap 5 ml Mylanta mengandung : 1. Magnesium Hidroksida berperan sebagai antasida untuk mengatasi tukak lambung dengan meningkatkan pH asam lambung melalui reaksi netralisasi. Senyawa ini juga memberikan perlindungan tambahan dari asam lambung dengan melapisi mukosa lambung menggunakan endapan koloid silika. 2. Aluminium Hidroksida (Al (OH)3) adalah zat yang be', 'mylanta.png', 'Antasid, Obat Antirefluks & Antiulserasi', 'Per 5 ml : Mg(OH)2 200 mg, Al(OH)3 200 mg, Simetikon 20 mg.', 'Refluks esofagitis, Rasa panas pada ulu hati, rasa tidak enak pada perut, gastritis, esofagitis peptikum, & hernia hiatus, kembung (gas), pemeriksaan endoskopik.', '3-4 x sehari 5-10 ml', '1 atau 2 jam sebelum/sesudah makan ', 'Simpan di tempat sejuk dan kering, terhindar dari sinar matahari langsung', 'Hipersentif, gangguan fungsi ginjal', 'Mual, sembelit, diare, atau sakit kepala', '1', 'PT. Bayer Indonesia', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi MYLANTA LIQ 150ML diambil dari berbagai macam sumber. ', 41980),
(67, 'MYLANTA TAB STR 10S', 'Mylanta merupakan obat yang digunakan untuk mengatasi penyakit-penyakit yang disebabkan oleh kelebihan produksi asam lambung, seperti sakit maag dan tukak lambung. Dalam 1 tab Mylanta mengandung : 1. Magnesium Hidroksida berperan sebagai antasida untuk mengatasi tukak lambung dengan meningkatkan pH asam lambung melalui reaksi netralisasi. Senyawa ini juga memberikan perlindungan tambahan dari asam lambung dengan melapisi mukosa lambung menggunakan endapan koloid silika. 2. Aluminium Hidroksida (Al (OH)3) adalah zat yang bekerja s', 'mylantatab.png', 'Antasid, Obat Antirefluks & Antiulserasi', 'Per tablet : Mg(OH)2 200 mg, Al(OH)3 200 mg, Simetikon 20 mg.', 'Refluks esofagitis, Rasa panas pada ulu hati, rasa tidak enak pada perut, gastritis, esofagitis peptikum, & hernia hiatus, kembung (gas), pemeriksaan endoskopik.', '3-4 x sehari 1-2 tablet', '1 atau 2 jam sebelum/sesudah makan', 'Simpan di tempat sejuk dan kering, terhindar dari sinar matahari langsung', 'Hipersentif', 'Mual, sembelit, diare, atau sakit kepala', '10', 'PT. Bayer Indonesia', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi MYLANTA TAB STR 10S diambil dari berbagai macam sumber. ', 7220),
(68, 'OMEPRAZOLE NOVELL 20MG CAP 30S', 'Omeprazole Novell merupakan obat generik dengan zat aktif Omeprazole yang digunakan untuk mengatasi penyakit-penyakit yang disebabkan oleh kelebihan produksi asam lambung, seperti sakit maag dan tukak lambung. Mekanisme kerja dari Omeprazole yaitu: â€¢ Omeprazole termasuk golongan PPI (Proton Pump Inhibitor) yang efektif bekerja dengan menghambat sekresi asam lambung melalui sistem enzim adenosin trifosfatase hidrogen-kalium (pompa proton) dari sel parietal lambung. \r\n', 'omeprazole.png', 'Antasid, Obat Antirefluks & Antiulserasi', 'Omeprazole', 'Terapi jangka pendekulkus duodenal dan lambung. Refluks esofagitis, sindroma Zollinger-Ellison', '> 12 th : 20 mg/hari selama 2-4 minggu. Pasien yang sukar disembuhkan dengan terapi : 40 mg/hari selama 4-8 minggu', 'Sebelum makan', 'Simpan ditempat sejuk dan kering, terlindung dari cahaya matahari', 'Hipersensif', 'Gangguan gastritis, sakit kepala, ruam kulit', '10', 'Novell Pharma', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi OMEPRAZOLE NOVELL 20MG CAP 30S diambil dari berbagai macam sumber. ', 564),
(69, 'SP THROCHES STRAW DOS 12&#39;S', 'SP Troches merupakan obat tablet hisap yang digunakan untuk mengobati kondisi radang di mulut seperti sariawan, radang gusi dan di daerah tenggorokan. \r\nSP Troches mengandung zat aktif Dequalinium Klorida yang bekerja sebagai antiseptik yang mampu menghambat pertumbuhan jamur dan bakteri khususnya pada rongga mulut dan tenggorokan. Degirol diaplikasikan dengan cara menghisap seperti permen sehingga diharapkan mampu bekerja secara langsung di daerah infeksi dan bermanfaat dalam melumasi dan menenangkan daerah yang sakit. \r\nBeli SP', 'troches.png', 'Preparat Mulut/Tenggorokan', 'Dequalinium chloride 0,25 mg', 'Infeksi bakteri dan fungi pada mulut dan tenggorokan', 'Hisap 1 tablet, perlahan lahan bila perlu 6-8 x sehari', 'Dihisap tanpa dikunyah', 'Simpan pada suhu 30Â°C, terhindar dari sinar matahari langsung dan jauhkan dari jangkauan anak-anak. ', '-', '-', '12', 'MEIJI', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi SP THROCHES STRAW DOS 12&#39;S diambil dari www.farmasiana.com. ', 9730),
(70, 'DEGIROL LOZ TAB 10S AMPLOP 10S', 'DEGIROL LOZ TAB 10S AMPLOP 10S merupakan obat preparat mulut dan tenggorokan dengan kandungan dequalinium chloride. Produk ini dapat digunakan untuk sakit tenggorokan, peradangan pada rongga mulut dan tenggorokan, infeksi selaput lendir mulut. Tersedia dalam bentuk tablet yang didistribusikan oleh Darya Varia. \r\nBeli DEGIROL LOZ TAB 10S AMPLOP 10S di TOBAT Online dan dapatkan manfaatnya.', 'degirol.png', 'Preparat Mulut/Tenggorokan', 'Dequalinium chloride ', 'Sakit tenggorokan, peradangan pada rongga mulut dan tenggorokan, infeksi selaput lendir mulut  ', '1 tablet tiap 3-4 jam, maksimum 8 tablet sehari   ', 'Dihisap', 'Simpan di tempat yang kering dan terhindar dari cahaya matahari. ', 'Hipersensitivitas komponen   ', '-', '10', 'PT.Darya-Varia', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi DEGIROL LOZ TAB 10S AMPLOP 10S diambil dari berbagai macam sumber. ', 11132),
(71, 'ALOCLAIR PLUS GEL 8ML', 'Gel untuk penyakit mulut dan tenggorokan.', 'aloclair.png', 'Preparat Mulut/Tenggorokan', 'Aqua, maltodextrin, propylene glycol, polyvinylpyrrolidone (PVP), aloe vera extr, K sorbate, Na benzoate, hydroxyethylcellulose, PEG 40, hydrogenated castor oil, disodium edetate, benzalkonium Cl, saccharin Na, Na hyaluronate, glycyrrhetic acid', 'Sariawan, luka pada bagian dalam mulut, setelah perlakuan pada gigi', '1-2 tetes 3-4 x sehari', '1-2 tetes dioleskan pada bagian yang luka', 'Hipersensitif', '-', '-', '1', '-', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi ALOCLAIR PLUS GEL 8ML diambil dari berbagai macam sumber. ', 103334),
(72, 'MINOSEP GARGLE 150ML', 'MINOSEP GARGLE 150ML merupakan obat kumur yang dapat digunakan untuk mencegah gingivitis, sariawan, bau mulut, menghambat pembentukan plak dan memelihara kebersihan mulut. \r\nBeli MINOSEP GARGLE 150ML di TOBAT Online dan dapatkan manfaatnya.', 'minosep.png', 'Preparat Mulut/Tenggorokan', 'Chlorhexidine gluconate', 'Mencegah gingivitis, sariawan, bau mulut, menghambat pembentukan plak, memelihara kebersihan mulut', '2x sehari gunakan 10 ml, kumur selama 1 menit', 'Untuk kumur', 'Simpan pada keadaan sejuk dan kering dan terhindar dari sinar matahari langsung.', 'Hipersensitif terhadap kompenen obat', '-', '1', 'Minorock', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi MINOSEP GARGLE 150ML diambil dari berbagai macam sumber. ', 50996),
(73, 'COOLING 5 SPRAY CHERRY 15ML', 'Cooling 5 merupakan antiseptik mulut dan tenggorokan yang dikemas dalam bentuk sediaan spray sehingga lebih mudah digunakan. Berfungsi untuk meredakan sakit tenggorokan karena kuman, merokok, gejala flu, perubahan cuaca, atau kurang minum.\r\n\r\nBeli Cooling 5 Spray cherry 15ml di TOBAT Online dan dapatkan berbagai manfaatnya. ', 'cooling.png', 'Preparat Mulut/Tenggorokan', 'Phenol crystal 1,4%', 'Membunuh kuman penyebab sakit tenggorokan, meredakan sakit tenggorokan karena terlalu banyak merokok, makan makanan yang berminyak, perubahan cuaca, banyak bicara atau berteriak, kurang minum, gejala flu dan pelega tenggorokan', 'Untuk setiap kali pemakaian, cukup disemprotkan 2-3 kali, semprotan dapat diulang tiap 3 jam sampai gejala reda.', 'Semprot tepat ke arah tenggorokan', '-', 'Semprotan jangan mengenai lidah', '-', '1', 'Novell Pharmaceutical Laboratories', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi COOLING 5 SPRAY CHERRY 15ML diambil dari berbagai macam sumber. ', 37576),
(74, 'HAU FUNG SAN', 'Hau Fung San merupakan ramuan obat herbal cina yang dapat digunakan untuk mengatasi sakit tenggorokan, sariawan dan sakit gigi\r\nBeli Hau Fung San di TOBAT Online dan dapatkan manfaatnya.', 'hau-fung-san.png', 'Preparat Mulut/Tenggorokan', '-', 'Untuk mengobati berbagai gangguan pada mulut dan tenggorokan seperti sariawa, sakit gigi, dan sakit tenggorokan', '2-3 kali tiap jam', 'Taburkan bubuk obat pada mulut atau tenggorokan yang sakit', '-', '-', '-', '1', '-', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi HAU FUNG SAN diambil dari berbagai macam sumber. ', 7211),
(75, 'EFISOL LIQUID 10ML', 'Larutan yang diindikasikan untuk Infeksi pada selaput lendir mulut (sariawan) dan rongga mulut dan nafas mulut bau akibat infeksi tersebut ', 'efisol.png', 'Preparat Mulut/Tenggorokan', 'Dequalinium Cl 5 mg, thymol 2.5 mg ', 'Infeksi pada selaput lendir mulut (sariawan) dan rongga mulut dan nafas mulut bau akibat infeksi tersebut ', 'Larutan 10-20 tetes dicampur air segelas 2-4 kali sehari. untuk sariawan: Oleskan tanpa diencerkan ', '-', '-', '-', '-', '1', 'Novell Pharma', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi EFISOL LIQUID 10ML diambil dari berbagai macam sumber. ', 35429),
(76, 'CANDISTIN SUSP DROP 12ML', 'Candistin Suspensi merupakan obat yang digunakan untuk mengobati sariawan di mulut akibat pertumbuhan jamur. Candistin mengandung zat aktif Nystatin yaitu obat anti jamur yang bekerja dengan merusak sel jamur dan menghentikan pertumbuhan jamur Candida pada rongga mulut, tenggorokan, usus, dan alat kelamin wanita.', 'candistin.png', 'Preparat Mulut/Tenggorokan', 'Nystatin 100.000IU', 'Pengobatan candidiasis pada rongga mulut', 'Bayi : 4 x 1-2ml sehari. Anak dan dewasa : 4 x 1-6ml sehari, pengobatan dilanjutkan 48 jam setelah gejala menghilang', 'Diteteskan pada rongga, baru kemudian di telan', 'Simpan di tempat sejuk dan kering, terhindar dari paparan sinar matahari langsung', 'Tidak boleh digunakan untuk terapi mikosis sistemik. Hentikan terapi jika timbul iritasi atau sensitiasi. Hamil dan laktasi', 'Diare, mual, muntah, gangguan GI, ruam, urtikaria, dan sangat jarang steven johnson syndrome', '1', '-', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi CANDISTIN SUSP DROP 12ML diambil dari berbagai macam sumber. ', 51195),
(77, 'LISTERINE NATURAL GREEN TEA 250ML', 'Anti septik kumur dengan rasa menyegarkan di mulut,aktif membunuh kuman penyebab plak, dan meredakan gusi berdarah. Gunakan setelah menyikat gigi untuk memberikan kesegaran napas sepanjang hari dan dapat menambah rasa percaya diri.', 'listrine.png', 'Preparat Mulut/Tenggorokan', 'Eucalyptol, menthol, methyl salicylate, thymol', 'Menghilangkan plak, dan bau mulut, menyegarkan pernafasan', '2 kali sehari 20 ml, setelah menyikat gigi', 'Hanya untuk kumur, jangan ditelan', '-', '-', '-', '1', '-', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi LISTERINE NATURAL GREEN TEA 250ML diambil dari berbagai macam sumber. ', 24961),
(78, 'OPPO KNEE SUPPORT W/HOLE 1021 L', 'Alat bantu OPPO digunakan di bagian lutut. Alat bantu OPPO ini didesain secara ideal dengan ketebalan lapisan neoprene yang terjepit di antara kapas kuat dan nilon yang membantu mempertahankan panas tubuh dan meningkatkan sirkulasi darah, sehingga mempercepat proses penyembuhan alami tubuh, menghilangkan rasa sakit, pembengkakan dan kekakuan dan membantu luka untuk pulih lebih cepat.Alat ini juga mengurangi risiko baru atau luka yang kambuh dengan menciptakan fleksibilitas yang lebih besar pada otot, tendon, dan ligamen. Alat kes', 'oppo.png', 'Alat Kesehatan Medis', '70% neoprene, 15% nylon, 15% cotton', 'Dengan design tumit dan ujung kaki yang terbuka sehingga memungkinkan untuk semua gerakan. Mengurangi rasa sakit akibat kaki yang tegang dan kaku. Memberikan kompresi untuk pergelangan kaki yang lemah atau tertekan. Membantu mempercepat penyembuhan pergel', 'Pegang bagian atas alat support dengan kedua tangan. Masukkan kaki ke dalam alam support dengan posisi tumit berada di bagian tumit. Tarik hingga lutut', '-', '-', 'Jangan menggunakan alat support ini setelah mengaplikasikan salep hangat atau panas', '-', '1', '-', 'Terakhir diperbarui pada 5 Mei 2019', 'Referensi OPPO KNEE SUPPORT W/HOLE 1021 L diambil dari berbagai macam sumber. ', 243815);

-- --------------------------------------------------------

--
-- Struktur dari tabel `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `nama` varchar(255) NOT NULL,
  `no_hp` bigint(255) NOT NULL,
  `alamat` varchar(255) NOT NULL,
  `sia` varchar(255) NOT NULL,
  `foto` varchar(255) NOT NULL DEFAULT 'default.svg',
  `level` int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data untuk tabel `user`
--

INSERT INTO `user` (`id`, `email`, `password`, `nama`, `no_hp`, `alamat`, `sia`, `foto`, `level`) VALUES
(3, 'syihabklayan@gmail.com', '$2y$10$lhz5ji5oepxNWrHvvzDyQeSA5518Ia0TIVWyIxFhkVSpXEgNTilc2', 'Syihab', 82218424651, 'Cirebon, Klayan', '', 'muzzamil.png', 0),
(4, 'syamfirdaus@gmail.com', '$2y$10$2vzTEtWmU2i31L21Nb7T5.NBwKrrBP0AwI3JBCkvf2a.I95PxXCVa', 'Muhammad Syam', 82218427432, 'tidaktahu', '', 'default.svg', 1),
(6, 'admin2@admin.com', '$2y$10$BLB4io4w62oSzHXhWX/JQOLfDwbvdmEuHzGiOR2HO.OErm7H12mWe', 'admin', 82218424650, 'Cirebon', '', 'bukan-antibiotik-kenali-4-jenis-obat-batuk-pilek-berdasarkan-gejala_m_-640x420.jpg', 1),
(7, 'syamfirdaus5@gmail.com', '$2y$10$KLlSYHYNu23o1svHOm/BAO1O50AZOmlOWssT3gq0zVWkVbBKBWDea', 'Syam', 77123123, 'Purwakarta', '', 'RFactory1DS-UnusedZavier.png', 0),
(12, 'kirito@sao.com', '$2y$10$stB.OZdqERIGhSQKEIvoGOmoduJNumhEhQZ.cL8G34TYadkjoR3Ue', 'Kirigaya Kazuto', 123, 'Aincard', '', 'default.svg', 1),
(14, 'apotik@apotik.com', '$2y$10$MstUbkY.9n3TBVyNLxwm..Lp8H2MgwxVLFt57ag7W85YrILRbTy0W', 'Apotik Sukaharga', 123, '123', '12EDWQ/213X/12X/123', 'SI TIKA Logo.png', 2),
(33, 'admin@admin.com', '$2y$10$GlKoiYZOggugizVFEqJICeaq8J8UZMll3Bno.K9oSo8dbOddwoWau', 'admin', 82218424650, '123', '', 'unsika.png', 1),
(35, 'syekh.syihabuddin17023@student.unsika.ac.id', '$2y$10$fNPiOsZBwsyl55L2DAbU4.OrBssj1d6JMQOAx5mgMM5JYzoDQvTAq', 'Syekh Syihabuddin Azmil Umri', 82218424650, 'Cirebon', '', 'maxresdefault.jpg', 0),
(36, 'apotik2@apotik.com', '$2y$10$ohq7bVGGnGwUJVWeu.b9.OFpeI1WvczLA8D51s/RF05zCLEC3hpau', 'APOTIK', 82218424650, '123', '12EDWQ/213X/12X/123', 'pray.png', 2),
(37, 'dummy@akun.com', '$2y$10$RN4PnhNyV9o9VIuB8TKEBOg3lQpYuxXrTiEpt7jJrBjFHmYxQU3XG', 'Dummy1', 82218424650, 'Cirebon', '', 'Oprec Panitia Diesnatalis.png', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `obat`
--
ALTER TABLE `obat`
  ADD PRIMARY KEY (`id_obat`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=38;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
